name: Generate Atom Feed

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write # Grants write permission to the `GITHUB_TOKEN`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create feeds directory if it does not exist
        run: mkdir -p feeds

      - name: Run the script
        env:
          HOLODEX_API_KEY: ${{ secrets.HOLODEX_API_KEY }}
        run: node generate_atom_feed2.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add feeds/holodex2.atom
          git commit -m 'Update Atom feed'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
