name: Update .gitignore and Clear Cache

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  update-gitignore-and-clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify .gitignore
        run: |
          cat .gitignore
        # Logs the content of .gitignore file

      - name: Clear Git Cache
        run: |
          git rm -r --cached .
          git add .
          git commit -m "Updated .gitignore to ignore files in feeds directory"
        # Clears git cache and commits changes

      - name: Check Repository Status
        run: |
          git status
        # Logs the current repository status

      - name: Push Changes
        if: github.ref == 'refs/heads/main'  # Ensure changes are pushed to the correct branch
        run: |
          git push origin ${{ github.ref }}
        # Pushes changes to the remote re sitory
