name: Parse Holodex Feed

on:
  workflow_dispatch:

jobs:
  parse-feed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install lxml requests

    - name: Extract Feed Data
      run: |
        import xml.etree.ElementTree as ET
        import requests

        feed_url = "https://raw.githubusercontent.com/braboobssiere/holedex-song-list/main/feeds/holodex.atom"
        response = requests.get(feed_url)
        root = ET.fromstring(response.content)

        ns = {'atom': 'http://www.w3.org/2005/Atom'}

        for entry in root.findall('atom:entry', ns):
            # Extract title
            title = entry.find('atom:title', ns).text.strip()
            
            # Extract video link
            link = entry.find("atom:link[@rel='alternate']", ns).attrib['href']
            
            # Extract summary
            summary = entry.find('atom:summary', ns).text.strip()
            
            print(f"Title: {title}")
            print(f"Link: {link}")
            print(f"Summary: {summary}\n{'='*50}\n")
      shell: python
