name: Holodex Feed Parser

on:
  workflow_dispatch:

jobs:
  parse-feed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up XML tools
      run: sudo apt-get install -y libxml2-utils

    - name: Process entries
      run: |
        FEED_URL="https://raw.githubusercontent.com/braboobssiere/holedex-song-list/refs/heads/main/feeds/holodex.atom"
        
        # Get all entries as plain XML
        curl -s "$FEED_URL" | xmllint --xpath "//*[local-name()='entry']" - > entries.xml

        # Process each entry
        count=$(xmllint --xpath "count(//*[local-name()='entry'])" entries.xml)
        echo "Found $count entries"

        for i in $(seq 1 $count); do
          echo "Processing entry $i/$count"
          
          # Extract fields using simple XPath
          id=$(xmllint --xpath "string((//*[local-name()='entry'])[$i]/*[local-name()='id']/text())" entries.xml)
          title=$(xmllint --xpath "string((//*[local-name()='entry'])[$i]/*[local-name()='title']/text())" entries.xml)
          link=$(xmllint --xpath "string((//*[local-name()='entry'])[$i]/*[local-name()='link'][@rel='alternate']/@href)" entries.xml)
          published=$(xmllint --xpath "string((//*[local-name()='entry'])[$i]/*[local-name()='published']/text())" entries.xml)
          author=$(xmllint --xpath "string((//*[local-name()='entry'])[$i]/*[local-name()='author']/*[local-name()='name']/text())" entries.xml)
          thumbnail=$(xmllint --xpath "string((//*[local-name()='entry'])[$i]/*[local-name()='link'][@rel='enclosure']/@href)" entries.xml)

          # Output results
          echo "Entry $i:"
          echo "ID: $id"
          echo "Title: $title"
          echo "URL: $link"
          echo "Published: $published"
          echo "Author: $author"
          echo "Thumbnail: $thumbnail"
          echo "------------------------------------"
        done
